### ISSUE TITLE
Mongoid

### ISSUE THREAD

**Issue by silvercrow27** [runtimerevolution/survey#23]
do you support mongoid in this gem?

**Comment by ivobenedito** [comment]
Hey @silvercrow27! 

Currently, we depend on ActiveRecord & a Relational DB supporting it and we're not expecting in a short term to add support for a Mongo ODM like Mongoid.

Having said that, you're totally free to fork it and replace ActiveRecord by Mongoid (it shouldn't be that hard).
If you do so and have interest in merging it back, ping us so that we can discuss how to integrate that into our gem. It would be a cool addition :) :+1:

**Comment by ivobenedito** [comment]
We're closing this issue for now, since we're not actively working on it.
We may re-open as soon as someone refreshes this topic with any contribution.
